// Converts the painted art in images/ (1-2 MB PNGs used by the text bot) into
// web-sized WebP for the Mini App under webapp/art/.
//
//   npm run art:build
//
// Uses Blender (see build.js) so no extra image tooling is needed.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { findBlender } from './build.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../..');
const IMAGES = path.join(ROOT, 'images');
const OUT = path.join(ROOT, 'webapp/art');

export const BOSSES = ['kivaha', 'avrora', 'fjorina', 'radjahal', 'carnevorusIsse'];
export const CLASSES = ['noClass', 'warrior', 'archer', 'mage', 'priest'];
export const GACHA_BANNERS = ['newbie', 'common', 'rare', 'royal', 'goddess'];

/** Main-menu feature id → painting. Features without one keep their icon. */
export const MENU_ART = Object.freeze({
  boss: 'bosses/kivaha/kivaha1-99.png',
  chest: 'misc/chestsGame.png',
  arena: 'misc/arena.png',
  shop: 'misc/shop.png',
  builds: 'misc/builds.png',
  steal: 'misc/stealResources.png',
  inventory: 'misc/inventory.png',
  gacha: 'gacha/goddess.png',
});

/**
 * Building paintings come in level stages named "<prefix><from>-<to>.png", some
 * in per-style subfolders (palace: common/elven/royal). Returns
 * { buildId: { style: [{ from, to, src, dst }] } }, style "default" when flat.
 */
export function buildStages(imagesDir = IMAGES) {
  const root = path.join(imagesDir, 'builds');
  const isDir = p => fs.statSync(p).isDirectory();
  const result = {};
  for (const id of fs.readdirSync(root)) {
    const dir = path.join(root, id);
    if (!isDir(dir)) continue;
    const subdirs = fs.readdirSync(dir).filter(name => isDir(path.join(dir, name)));
    const styles = subdirs.length ? subdirs.map(style => [style, path.join(dir, style)]) : [['default', dir]];
    for (const [style, styleDir] of styles) {
      const stages = [];
      for (const file of fs.readdirSync(styleDir)) {
        const match = file.match(/(\d+)-(\d+)\.png$/i);
        if (!match) continue;
        const from = Number(match[1]), to = Number(match[2]);
        stages.push({
          from, to,
          src: path.relative(imagesDir, path.join(styleDir, file)).split(path.sep).join('/'),
          dst: `builds/${id}/${style}-${from}-${to}.webp`,
        });
      }
      if (stages.length) (result[id] ||= {})[style] = stages.sort((a, b) => a.from - b.from);
    }
  }
  return result;
}

/** Source of webapp/art/builds-art.js: the level -> painting lookup for the city screen. */
export function buildArtModule(stages = buildStages()) {
  const map = {};
  for (const [id, styles] of Object.entries(stages)) {
    map[id] = Object.fromEntries(Object.entries(styles).map(([style, list]) => [style, list.map(({ from, to, dst }) => ({ from, to, url: `/art/${dst}` }))]));
  }
  return `// Generated by \`npm run art:build\` (scripts/blender/art.js). Do not edit.
// JS rather than JSON because *.json is gitignored in this repo.
export const BUILD_ART = ${JSON.stringify(map, null, 2)};

/** Painting for a building at \`level\`; unknown styles fall back to the first one. */
export function buildArtUrl(id, level = 1, style = null) {
  const styles = BUILD_ART[id];
  if (!styles) return null;
  const stages = styles[style] || styles.default || Object.values(styles)[0];
  const lvl = Math.max(1, Number(level) || 1);
  const stage = stages.find(s => lvl >= s.from && lvl <= s.to) || (lvl < stages[0].from ? stages[0] : stages[stages.length - 1]);
  return stage.url;
}
`;
}

export function artJobs() {
  const jobs = [];
  for (const styles of Object.values(buildStages())) {
    for (const list of Object.values(styles)) for (const stage of list) jobs.push({ src: stage.src, dst: stage.dst, size: 560, quality: 78 });
  }
  for (const boss of BOSSES) jobs.push({ src: `bosses/${boss}/${boss}1-99.png`, dst: `bosses/${boss}.webp`, size: 960, quality: 84 });
  for (const [feature, src] of Object.entries(MENU_ART)) jobs.push({ src, dst: `menu/${feature}.webp`, size: 480, quality: 78 });
  for (const cls of CLASSES) for (const gender of ['male', 'female']) jobs.push({ src: `classes/${cls}/${gender}/${cls}.png`, dst: `classes/${cls}-${gender}.webp`, size: 640, quality: 80 });
  jobs.push({ src: 'misc/chestsGame.png', dst: 'chests/backdrop.webp', size: 960, quality: 80 });
  for (const banner of GACHA_BANNERS) jobs.push({ src: `gacha/${banner}.png`, dst: `gacha/${banner}.webp`, size: 720, quality: 80 });
  return jobs;
}

function main() {
  const blender = findBlender();
  if (!blender) {
    console.error('Blender not found. Install it or set BLENDER_PATH.');
    process.exit(1);
  }
  const jobs = artJobs().map(job => ({ ...job, src: path.join(IMAGES, job.src), dst: path.join(OUT, job.dst) }));
  const missing = jobs.filter(job => !fs.existsSync(job.src));
  if (missing.length) {
    console.error(`Missing source art:\n${missing.map(job => job.src).join('\n')}`);
    process.exit(1);
  }
  const jobsFile = path.join(os.tmpdir(), `art-jobs-${process.pid}.json`);
  fs.writeFileSync(jobsFile, JSON.stringify(jobs));
  const result = spawnSync(blender, ['--background', '--factory-startup', '--python', path.join(HERE, 'convert_art.py'), '--', jobsFile], { encoding: 'utf8' });
  fs.rmSync(jobsFile, { force: true });
  const done = (result.stdout.match(/CONVERTED /g) || []).length;
  if (result.status !== 0 || done !== jobs.length) {
    console.error(result.stdout.slice(-3000), result.stderr.slice(-2000));
    process.exit(1);
  }
  fs.writeFileSync(path.join(OUT, 'builds-art.js'), buildArtModule());
  let total = 0;
  for (const job of jobs) total += fs.statSync(job.dst).size;
  console.log(`✓ ${done} images → webapp/art (${Math.round(total / 1024)} KB total)`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
