import {buildPromotedClasses} from './classTree.js';

// tier 1 = base classes (chosen freely); tier 2/3 are professions reached by quest
// (see classTree.js / classQuestsTemplate.js) and are generated from their parent.
const baseClasses = [{
    name: "noClass",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс без определенной специализации, представляет собой бродягу, который не обладает выдающимися навыками или способностями",
    translateName: "Бродяжка",
    attack: 1,
    defence: 1,
    criticalDamage: 1,
    criticalChance: 1,
    incomingDamageModifier: 1,
    additionalDamageMul: 1,
    maxHp: 1000,
    maxCp: 200,
    maxMp: 200,
    mp: 200,
    cp: 200,
    hp: 1000,
    hpRestoreSpeed: 5, // единиц в секунду
    mpRestoreSpeed: 2, // единиц в секунду
    cpRestoreSpeed: 1, // единиц в секунду
    speed: 1,
    block: 1,
    accuracy: 1,
    evasion: 1
}, {
    name: "warrior",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-воин с высокой защитой и силой атаки, предназначенный для ближнего боя",
    translateName: "Паладин",
    attack: 1.54,
    defence: 3.2,
    criticalChance: 14.5,
    criticalDamage: 1.2,
    incomingDamageModifier: 1 - 0.1,
    additionalDamageMul: 1,
    maxHp: 4100,
    maxCp: 550,
    maxMp: 400,
    mp: 400,
    cp: 550,
    hp: 4100,
    hpRestoreSpeed: 4,
    mpRestoreSpeed: 2,
    cpRestoreSpeed: 4,
    speed: 104,
    block: 87,
    accuracy: 60,
    evasion: 30
}, {
    name: "mage",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-маг, специализирующийся на магических атаках и обладающий высокой скоростью и маной",
    translateName: "Маг",
    attack: 5.19,
    defence: 2,
    criticalChance: 28.5,
    criticalDamage: 1.3,
    incomingDamageModifier: 1 + 0.1,
    additionalDamageMul: 1 + 0.05,
    maxHp: 2000,
    maxCp: 430,
    maxMp: 650,
    cp: 430,
    mp: 650,
    hp: 2000,
    hpRestoreSpeed: 2,
    mpRestoreSpeed: 5,
    cpRestoreSpeed: 3,
    speed: 116,
    block: 31,
    accuracy: 108,
    evasion: 36
}, {
    name: "priest",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-жрец, обладающий высокой выносливостью и защитой, а также способностью исцелять союзников",
    translateName: "Прист",
    attack: 1.44,
    defence: 4.88,
    criticalChance: 5.58,
    criticalDamage: 1.2,
    incomingDamageModifier: 1 - 0.05,
    additionalDamageMul: 1 - 0.1,
    maxHp: 3362,
    maxCp: 780,
    maxMp: 800,
    mp: 800,
    cp: 780,
    hp: 3362,
    hpRestoreSpeed: 2,
    mpRestoreSpeed: 3.2,
    cpRestoreSpeed: 3,
    speed: 108,
    block: 105,
    accuracy: 46,
    evasion: 53
}, {
    name: "archer",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-лучник, способный наносить высокий физический урон с дальней дистанции.",
    translateName: "Лучник",
    attack: 5.31,
    defence: 0.77,
    criticalChance: 18.77,
    criticalDamage: 1.4,
    incomingDamageModifier: 1 + 0.02,
    additionalDamageMul: 1 + 0.15,
    maxHp: 3168,
    maxCp: 400,
    maxMp: 500,
    mp: 500,
    cp: 400,
    hp: 3168,
    hpRestoreSpeed: 2,
    mpRestoreSpeed: 3,
    cpRestoreSpeed: 2,
    speed: 142,
    block: 10,
    accuracy: 113,
    evasion: 77
}, {
    name: "rogue",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-разбойник: молниеносные удары кинжалами, огромный шанс критического урона и ловкость, но почти никакой брони.",
    translateName: "Разбойник",
    attack: 3.19,
    defence: 1.27,
    criticalChance: 19.54,
    criticalDamage: 1.45,
    incomingDamageModifier: 1 + 0.04,
    additionalDamageMul: 1 + 0.08,
    maxHp: 2800,
    maxCp: 420,
    maxMp: 480,
    mp: 480,
    cp: 420,
    hp: 2800,
    hpRestoreSpeed: 2,
    mpRestoreSpeed: 3,
    cpRestoreSpeed: 2,
    speed: 150,
    block: 7,
    accuracy: 105,
    evasion: 100
}, {
    name: "berserk",
    tier: 1,
    parent: null,
    promoteLvl: 0,
    description: "Класс-берсерк: платит здоровьем за чудовищную силу. Высокий запас HP, серии ударов и вампиризм.",
    translateName: "Берсерк",
    attack: 3.28,
    defence: 1.72,
    criticalChance: 12.74,
    criticalDamage: 1.35,
    incomingDamageModifier: 1 + 0.04,
    additionalDamageMul: 1 + 0.1,
    maxHp: 3772,
    maxCp: 700,
    maxMp: 300,
    mp: 300,
    cp: 700,
    hp: 3772,
    hpRestoreSpeed: 3,
    mpRestoreSpeed: 2,
    cpRestoreSpeed: 3,
    speed: 108,
    block: 39,
    accuracy: 83,
    evasion: 25
}];

// `family` is the combat line of a class (mage line, priest line, ...). The six family blocks are the stat
// blocks the real start classes and professions are built from (classTree.js); only `noClass` stays a class.
for (const base of baseClasses) base.family = base.name;

// The six family blocks stay in the list as `legacy` classes: characters and tools of the old tree still name
// them (migrateSessionClass moves a character to a real class); they are never offered for a choice.
const familyBlocks = baseClasses.filter(base => base.name !== 'noClass').map(base => ({...base}));
for (const base of baseClasses) if (base.name !== 'noClass') base.legacy = true;
export const FAMILY_BLOCKS = familyBlocks;
export default [...baseClasses, ...buildPromotedClasses(familyBlocks)];
