//1 power == 5% dmg. if power == 5, then damage will be 100% + 25%
//cost values is in crystals
//cooldown - attack CD in seconds;

export default {
    noClass: [{
        slot: 0,
        name: "Тык палкой",
        description: "Тыкнуть палкой в босса.",
        effect: "common_attack",
        damageModifier: 1,
        cooldown: 0,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 0,
        costHp: 0,
        cost: 0,
        cooldownReceive: 0
    }],
    warrior: [{
        slot: 0,
        name: "Взмах меча",
        description: "Быстрый удар мечом.",
        effect: "common_attack",
        cooldown: 0,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 1,
        cost: 2,
        costHp: 0
    }, {
        slot: 1,
        name: "Ярость вампира",
        description: "Призыв магии крови: наносит 140% урона врагу, вампиря себе здоровье в количестве равное 5% от нанесённого урона.",
        effect: "vampire",
        vampirePower: 0.05,
        damageModifier: 1.4,
        cooldown: 22,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 9,
        costHp: 0,
        cost: 36
    }, {
        slot: 2,
        name: "Вожделение паладина",
        description: "Ты собираешь всю волю в кулак и совершаешь мощный удар, который наносит 350% урона.",
        effect: "strong_attack",
        damageModifier: 3.5,
        cooldown: 47,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 15,
        costHp: 0,
        cost: 80
    }],
    mage: [{
        slot: 0,
        name: "Выстрел из посоха",
        description: "Выстрел из посоха нейтральной стихией.",
        effect: "common_attack",
        cooldown: 0,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 1,
        costHp: 0,
        cost: 5
    }, {
        slot: 1,
        name: "Грозовая стужа",
        description: "Запуск огромного грозового вихря, сопровождающегося ледяными шипами. Наносит 500% урона.",
        effect: "magic_attack",
        damageModifier: 5,
        cooldown: 18,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 10,
        costHp: 0,
        cost: 43
    }, {
        slot: 2,
        name: "Лунная тень",
        description: "Создаёт щит на 45% от хп.",
        effect: "shield",
        shieldPower: 0.45,
        cooldown: 120,
        isSelf: true,
        isDealDamage: false,
        isHeal: false,
        isShield: true,
        isBuff: false,
        needLvl: 15,
        costHp: 0,
        cost: 67
    }],
    priest: [{
        slot: 0,
        name: "Удар скипетром",
        description: "Удар скипетром по болевым точкам врага.",
        effect: "common_attack",
        cooldown: 0,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 1,
        costHp: 0,
        cost: 3
    }, {
        slot: 1,
        name: "Сияние утренней звезды",
        description: "Призыв святой энергии, которая исцеляет раны. Восстанавливает тебе 25% хп.",
        effect: "heal",
        healPower: 0.25,
        cooldown: 15,
        isSelf: true,
        isDealDamage: false,
        isHeal: true,
        isShield: false,
        isBuff: false,
        needLvl: 8,
        costHp: 0,
        cost: 68
    }, {
        slot: 2,
        name: "Казнь святых",
        description: "Меч из чистой энергии света поражает твоего врага, нанося ему 200% урона",
        effect: "magic_attack",
        damageModifier: 2,
        cooldown: 32,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 15,
        costHp: 600,
        cost: 0
    }],
    archer: [{
        slot: 0,
        name: "Точный выстрел",
        description: "Выстрел из лука.",
        effect: "common_attack",
        cooldown: 0,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 1,
        costHp: 0,
        cost: 1
    }, {
        slot: 1,
        name: "Прямо в яблочко",
        description: "Выстрел, который наносит 300% урона.",
        effect: "strong_attack",
        damageModifier: 3,
        cooldown: 12,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 12,
        costHp: 0,
        cost: 55
    }, {
        slot: 2,
        name: "Элементальная стрела",
        description: "Мощный выстрел трёх стрел трёх разных стихий. Наносит 1000% урона.",
        effect: "magic_attack",
        damageModifier: 10,
        cooldown: 180,
        isSelf: false,
        isDealDamage: true,
        isHeal: false,
        isShield: false,
        isBuff: false,
        needLvl: 15,
        costHp: 0,
        cost: 102
    }]
};