// Content hashes of the template/*.js seeds. Generated by scripts/templates/hash.mjs;
// test/templates.test.js fails when a template changes without a version bump + new hash.
export default {
    arenaWeeklyPrizes: 'ebe845ce738b46fcdd4cb7c5259f6b2e7c818daf',
    bossAttacks: '0e60f7bed9c508fb29c8b67cc23c6f0ca86c1cab',
    bossLoot: '20253cd42db116e6bdd3bbcac0ea81d87863fdba',
    bossSkills: '3190e1ac14fb9c8c62450401897902a7c98e65e6',
    bosses: 'e8fbe9b6d67eb6589c7a21ac60d920b72e80edee',
    builds: '630908a59eac02e3159d45f3fac9a9fda1a86971',
    chanceToHit: '94e7e762fa16259c9a0e4b09da4dd53252f239cb',
    clanApplicationConditions: 'ead98d421cba3223befcb8d08a6570f240c00d34',
    classSkills: '55f27438454fafae96eaa3694e13fbc33ab1c54d',
    classStats: '24fae9b027765a66d03119f97a47ecddb274ed46',
    elements: '13f9b0fa6d48788b929c6f9122301585512e70b4',
    elementsSynergy: '11691c0fe9efe7de3a4c8eb233722c64ca98d2f3',
    equipmentBonusStats: '9786db8930f74805ba2624d211c3021f295bb81c',
    equipment: '3839d5c31a97034aa949b89d6c43f8e22e43caeb',
    gacha: 'f69cf64d7d78e2e8bac157f1c403bbf8b21eec2e',
    levels: '56c98426f907cf14420c4932cb89eee34617071c',
    potions: 'de562c9ab8695500ed6c823a002a4d7bb0bdb6b1',
    pvpSign: '3d59ea38a7317f5aa8410df1fa1002c5903033d6',
    shop: 'b14e7e2e150e9b2128198de9c45cbe0c8bf84d06',
};
