// Content hashes of the template/*.js seeds. Generated by scripts/templates/hash.mjs;
// test/templates.test.js fails when a template changes without a version bump + new hash.
export default {
    arenaWeeklyPrizes: 'ebe845ce738b46fcdd4cb7c5259f6b2e7c818daf',
    bossAttacks: '6e468fb700da67af689a4df9e9b8e47df00ba16b',
    bossLoot: 'c37316f6c5599c9b5a1df240c1b9ed690241f0e2',
    bossSkills: '3190e1ac14fb9c8c62450401897902a7c98e65e6',
    bosses: '3228db55c87f432c5e6c6334451d07b6b5c816a3',
    builds: '82fee7da4da167a2dec7565ff7d2ef0f0027402e',
    chanceToHit: '94e7e762fa16259c9a0e4b09da4dd53252f239cb',
    clanApplicationConditions: 'ead98d421cba3223befcb8d08a6570f240c00d34',
    classQuests: '425a194ecc0f9b7ad6e6baff0d4403cd129fd4da',
    classSkills: '6b5c51fbd665190fae17b2a69bedae78ab98b0fd',
    classStats: '7c1ac79f8accd016c98d9cf5ca7b354336209037',
    elements: '13f9b0fa6d48788b929c6f9122301585512e70b4',
    elementsSynergy: '11691c0fe9efe7de3a4c8eb233722c64ca98d2f3',
    equipment: 'b87b374b677770639f38078df7312d12966f76e0',
    gacha: '27ad6b31182582c9c64cd4ffc9f0f299912cfe13',
    levels: '13ff4ec3b0927f7ad6de23b1c94e22d1722a3610',
    materials: '949a86d6438154e7d966992cfd2ef1ae57717fea',
    potions: '5fa80eee2a5056a6bff07cef79b3bcc29d019df6',
    pvpSign: '3d59ea38a7317f5aa8410df1fa1002c5903033d6',
    shop: '8e037c3d4da83eaa34d2ea7718c42fe89516e204',
};
