// Content hashes of the template/*.js seeds. Generated by scripts/templates/hash.mjs;
// test/templates.test.js fails when a template changes without a version bump + new hash.
export default {
    arenaWeeklyPrizes: 'ebe845ce738b46fcdd4cb7c5259f6b2e7c818daf',
    bossAttacks: '6e468fb700da67af689a4df9e9b8e47df00ba16b',
    bossLoot: 'c37316f6c5599c9b5a1df240c1b9ed690241f0e2',
    bossSkills: '3190e1ac14fb9c8c62450401897902a7c98e65e6',
    bosses: '3228db55c87f432c5e6c6334451d07b6b5c816a3',
    builds: '630908a59eac02e3159d45f3fac9a9fda1a86971',
    chanceToHit: '94e7e762fa16259c9a0e4b09da4dd53252f239cb',
    clanApplicationConditions: 'ead98d421cba3223befcb8d08a6570f240c00d34',
    classQuests: 'bc248544fc2a5ec58570222359a26a3b9ff5c525',
    classSkills: 'f58454643affcbe822fe0d423ce72a9f96d1f425',
    classStats: '6bcd6e3622d72a7cc2da2efe4b10732b526dea75',
    elements: '13f9b0fa6d48788b929c6f9122301585512e70b4',
    elementsSynergy: '11691c0fe9efe7de3a4c8eb233722c64ca98d2f3',
    equipment: '9c11791f03bde66fad4e991b337df4ea4885df57',
    gacha: '27ad6b31182582c9c64cd4ffc9f0f299912cfe13',
    levels: '56c98426f907cf14420c4932cb89eee34617071c',
    materials: 'ee48acfa02c16659898a4905ce28d826ea75c011',
    potions: '5fa80eee2a5056a6bff07cef79b3bcc29d019df6',
    pvpSign: '3d59ea38a7317f5aa8410df1fa1002c5903033d6',
    shop: '2a45f77e86218ec9bf2634a33a971d691dee4f58',
};
