import json,html
from pathlib import Path
data=json.loads(Path('docs/l2-effects-references.json').read_text(encoding='utf-8'))
rows=data['effects']
Path('docs/l2-effects-preview.html').write_text('''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>High Five — все баффы и дебаффы</title><style>
*{box-sizing:border-box}body{margin:0;padding:20px;background:#111411;color:#ded8be;font:14px system-ui}h1{font:26px Georgia;color:#ecd69c}a{color:#dec582}.filters{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}input,select,button{padding:10px;background:#20251e;color:#eee;border:1px solid #726445;border-radius:4px}input{flex:1 1 230px;min-width:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,270px),1fr));gap:8px}article{display:flex;align-items:center;gap:10px;min-width:0;padding:10px;background:#20231b;border:1px solid #4f4837}img,.missing{width:32px;height:32px;image-rendering:pixelated;flex-shrink:0}.missing{display:grid;place-items:center;background:#171914;border:1px dashed #726445;color:#8a806c}article div{min-width:0}small,code{display:block;color:#a8a391;font-size:11px;overflow-wrap:anywhere}b{font-size:13px}.nav{display:flex;align-items:center;justify-content:center;gap:12px;margin:16px 0}#count{color:#e3cd95}
</style><h1>High Five · все баффы и дебаффы</h1><p>Полный каталог оригинальных записей эффектов, включая песни, танцы, переключаемые умения, эффекты предметов и NPC. Одинаковые значки у разных уровней и вариантов сохранены как в клиенте.</p><p>Часть серверных записей не имеет изображения в предоставленных ассетах — они отмечены явно. Игровые классы получают свои умения по оригинальным деревьям обучения; каталог также содержит эффекты для других контекстов.</p><p><a href="l2-skill-fishing-icons-preview.html">Навыки и рыбалка</a> · <a href="l2-effects-references.json">Соответствия и отсутствующие изображения</a></p><div class="filters"><input id="search" aria-label="Поиск" placeholder="Название, ID, группа эффекта или имя иконки"><select id="kind" aria-label="Тип"><option value="">Все эффекты</option value="buff">Баффы</option><option value="debuff">Дебаффы</option></select><select id="group" aria-label="Группа"><option value="">Все группы</option><option>Песни</option><option>Танцы</option><option>Переключаемые умения</option></select><select id="scope" aria-label="Источник"><option value="">Все источники</option><option value="player">Персонажи</option><option value="item">Предметы / ЛС</option><option value="npc">NPC</option><option value="special">Особые</option></select><select id="art" aria-label="Изображение"><option value="">Все записи</option><option value="yes">С изображением</option><option value="no">Без изображения</option></select></div><p id="count"></p><div class="grid"></div><div class="nav"><button id="prev">←</button><span id="page"></span><button id="next">→</button></div><script>
const rows='''+json.dumps(rows,ensure_ascii=False)+''';let page=0;const size=120;const q=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function render(){const needle=q('search').value.trim().toLowerCase();const found=rows.filter(r=>(!q('kind').value||r.kind===q('kind').value)&&(!q('group').value||r.group===q('group').value)&&(!q('scope').value||r.scope===q('scope').value)&&(!q('art').value||Boolean(r.art)===(q('art').value==='yes'))&&[r.name,r.id,r.abnormalType,r.icon].join(' ').toLowerCase().includes(needle));const pages=Math.max(1,Math.ceil(found.length/size));page=Math.max(0,Math.min(page,pages-1));q('count').textContent=`Найдено ${found.length} / ${rows.length} записей · с изображением ${found.filter(r=>r.art).length}`;document.querySelector('.grid').innerHTML=found.slice(page*size,page*size+size).map(r=>`<article data-id="${r.id}">${r.art?`<img src="../webapp/art/l2-effects/${r.art}-32.webp" alt="">`:'<span class="missing" title="Нет в предоставленных ассетах">?</span>'}<div><b>${esc(r.name)}</b><small>${r.id} · ${esc(r.group)} · ${r.levels} ур.</small><small>${esc(r.abnormalType||r.operate)}</small><code>${esc(r.art?r.icon:'Нет изображения в ассетах')}</code></div></article>`).join('');q('page').textContent=`${page+1} / ${pages}`;q('prev').disabled=page===0;q('next').disabled=page+1>=pages;};for(const id of ['search','kind','group','scope','art'])q(id).addEventListener('input',()=>{page=0;render()});q('prev').onclick=()=>{page--;render()};q('next').onclick=()=>{page++;render()};render();</script></html>''',encoding='utf-8')
for filename in ['docs/l2-skill-fishing-icons-preview.html','scripts/l2j/publish-skill-fishing-icons.py']:
    p=Path(filename);s=p.read_text(encoding='utf-8');old='<a href="l2-assets-preview.html">Все ассеты</a>';new=old+' · <a href="l2-effects-preview.html">Все баффы и дебаффы High Five</a>'
    if 'href="l2-effects-preview.html"' not in s:s=s.replace(old,new);p.write_text(s,encoding='utf-8')
print(f'Published searchable catalogue: {len(rows)} records.')
