"""Convert original client PNGs to lossless WebP without repainting their pixels."""
import json
from pathlib import Path
from PIL import Image
plan=json.loads(Path('.tmp/l2-icon-import-plan.json').read_text(encoding='utf-8'))
dest=Path('webapp/art/l2');dest.mkdir(parents=True,exist_ok=True)
expected={f"{a['key']}-{size}.webp" for a in plan['assets'] for size in a['sizes']}
assert dest.resolve().is_relative_to(Path.cwd().resolve())
for stale in dest.glob('*.webp'):
    if stale.name not in expected:stale.unlink()
for asset in plan['assets']:
    with Image.open(asset['source']) as original:
        original.load()
        asset['originalSize']=list(original.size)
        for size in asset['sizes']:
            target=dest/f"{asset['key']}-{size}.webp"
            if not target.exists():original.convert('RGBA').resize((size,size),Image.Resampling.NEAREST).save(target,lossless=True)
exports={'L2_MATERIAL_ART':plan['materials'],'L2_JEWELRY_ART':plan['catalog'],'L2_JEWELRY_IDENTITIES':plan['identities'],'L2_ITEM_IDENTITIES':plan['equipment'],'L2_CATEGORY_ART':plan['categories'],'L2_UI_ART':plan['ui']}
Path('webapp/art/l2-icon-art.js').write_text('// Original local Lineage II client icons. Generated by scripts/l2j/import-local-icons.mjs.\n'+''.join(f'export const {name}=Object.freeze({json.dumps(value,ensure_ascii=False)});\n' for name,value in exports.items())+'''
const published=new Set([...Object.values(L2_MATERIAL_ART),...Object.values(L2_JEWELRY_ART),...Object.values(L2_ITEM_IDENTITIES),...Object.values(L2_CATEGORY_ART),...Object.values(L2_UI_ART)]);
export function l2IconUrl(key,size=128){return published.has(key)?`/art/l2/${key}-${[128,256,512].includes(size)?size:128}.webp`:null;}
export function l2MaterialIcon(key){const art=L2_MATERIAL_ART[key];return art?l2IconHtml(art):'';}
export function l2IconHtml(key){const src=l2IconUrl(key);return src?`<img class="mat-icon l2-client-icon" src="${src}" srcset="${src} 1x, ${l2IconUrl(key,256)} 2x" width="22" height="22" alt="" loading="lazy" decoding="async" draggable="false">`:'';}
export function l2CategoryIcon(kind){return l2IconHtml(L2_CATEGORY_ART[kind]);}
''',encoding='utf-8')
Path('art-source/l2-redraw/sources.json').write_text(json.dumps([{k:v for k,v in a.items() if k!='source'} for a in plan['assets']],ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
# Compatibility paths used by the standalone prototypes and older UI consumers.
# Equipment paintings are intentionally excluded.
import shutil
aliases={'scroll':'scroll_S','scroll-blessed':'blessed_S','scroll-safe':'safe_weapon_S','crystal':'crystal_S','gem':'craft_gem_S','binder':'craft_binder_S','leather':'craft_leather_S','fiber':'craft_fiber_S','lifestone':'lifestone_C','soulshot':'soulshot_S','spiritshot':'spiritshot_S','blessed-spiritshot':'blessed_spiritshot_S'}
aliases.update({f'attr-{tier}':f'attr_{tier}_fire' for tier in ['stone','crystal','jewel']})
aliases.update({f'egg-{kind}':f'egg_{kind}' for kind in ['wyvern','dragon','ancient']})
for alias,key in aliases.items():
    for size in [128,256]:shutil.copyfile(dest/f"{plan['materials'][key]}-{size}.webp",Path('webapp/art/icons')/f'{alias}-{size}.webp')
for key,art in plan['materials'].items():
    if key.startswith('potion-'):
        for size in [128,256,512]:
            target=Path('webapp/art/items/v1')/f'{key}-{size}.webp'
            if target.exists():shutil.copyfile(dest/f'{art}-{size}.webp',target)
for size in [128,256]:shutil.copyfile(dest/f"{plan['ui']['coin']}-{size}.webp",Path('webapp/art/ui/v1')/f'coin-{size}.webp')
print(f"Converted {len(plan['assets'])} original client icons; all catalogue equipment mapped to L2 icons.")
