// Real High Five loot and crafting data for the hunting fields and catacombs.
//
//   node scripts/l2j/extract-loot.mjs <npcs dir> <items dir> <Recipes.xml>
//
// npcs dir   : data/stats/npcs of a High Five datapack (flat <drop> lists, per-item chance already includes the group)
// items dir  : data/stats/items (names, types, grades, shop prices)
// Recipes.xml: data/Recipes.xml
// Writes template/l2Loot.js (drop tables by npc id), template/l2Items.js (names/prices of every item they mention) and
// template/l2Recipes.js (every craft recipe with its real ingredients).
import fs from 'node:fs';
import path from 'node:path';
import huntingTemplate from '../../template/huntingTemplate.js';
import catacombs from '../../template/catacombsTemplate.js';

const [npcDir, itemDir, recipeFile] = process.argv.slice(2);
if (!npcDir || !itemDir || !recipeFile) { console.error('usage: node scripts/l2j/extract-loot.mjs <npcs dir> <items dir> <Recipes.xml>'); process.exit(1); }
const walk = dir => fs.readdirSync(dir, {withFileTypes: true}).flatMap(e => e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]);
const clean = name => name.replaceAll('&apos;', "'").replaceAll('&lt;', '<').replaceAll('&gt;', '>').replaceAll('&amp;', '&');

// ---- items
const items = new Map();
for (const file of walk(itemDir).filter(f => f.endsWith('.xml'))) {
  for (const m of fs.readFileSync(file, 'utf8').matchAll(/<item id="(\d+)" type="(\w+)" name="([^"]*)">([\s\S]*?)<\/item>/g)) {
    const body = m[4], set = name => body.match(new RegExp(`<set name="${name}" val="([^"]*)"`))?.[1];
    items.set(m[1], {id: +m[1], name: clean(m[3]), type: m[2], grade: set('crystal_type') || 'NONE', price: +(set('price') || 0), etc: set('etcitem_type') || null, stackable: set('is_stackable') === 'true'});
  }
}

// ---- drop tables of the mobs that really are in our zones
const wanted = new Set([...huntingTemplate, ...catacombs].flatMap(zone => zone.mobs.map(mob => String(mob.id))));
const loot = {};
const used = new Set();
for (const file of fs.readdirSync(npcDir).filter(f => f.endsWith('.xml'))) {
  for (const m of fs.readFileSync(path.join(npcDir, file), 'utf8').matchAll(/<npc id="(\d+)"[^>]*>([\s\S]*?)<\/npc>/g)) {
    if (!wanted.has(m[1])) continue;
    const drop = m[2].match(/<drop>([\s\S]*?)<\/drop>/)?.[1] || '';
    const rows = [...drop.matchAll(/<item id="(\d+)" min="(\d+)" max="(\d+)" chance="([\d.]+)"/g)]
      .filter(x => x[1] !== '57' && +x[4] > 0)
      .map(x => [+x[1], +x[2], +x[3], Math.round(+x[4] * 100000) / 100000]);
    loot[m[1]] = rows;
    rows.forEach(row => used.add(String(row[0])));
  }
}

// ---- recipes: the recipe item (recipeId) is what the player learns; ingredients and product are plain items
const recipes = [];
const xml = fs.readFileSync(recipeFile, 'utf8');
for (const m of xml.matchAll(/<item id="(\d+)" recipeId="(\d+)" name="([^"]*)" craftLevel="(\d+)" type="(\w+)" successRate="(\d+)">([\s\S]*?)<\/item>/g)) {
  const body = m[7], production = body.match(/<production id="(\d+)" count="(\d+)"/);
  if (!production) continue;
  const ingredients = [...body.matchAll(/<ingredient id="(\d+)" count="(\d+)"/g)].map(x => [+x[1], +x[2]]);
  recipes.push({recipeItem: +m[2], level: +m[4], kind: m[5], rate: +m[6], mp: +(body.match(/statUse name="MP" value="(\d+)"/)?.[1] || 0),
    product: +production[1], amount: +production[2], ingredients});
}
// recipes are only useful when the player can reach them: the product feeds from a drop or another recipe
const itemsOut = {};
const keep = id => { const item = items.get(String(id)); if (item) itemsOut[id] = [item.name, item.type, item.grade, item.price, item.etc]; };
used.forEach(keep);
recipes.forEach(r => { keep(r.recipeItem); keep(r.product); r.ingredients.forEach(([id]) => keep(id)); });
keep(57); keep(5575);

const write = (file, comment, name, value) => fs.writeFileSync(file, `// ${comment}\nexport default ${JSON.stringify(value)};\n`);
write('template/l2Loot.js', 'Real High Five drop tables [itemId, min, max, chance %] by npc id. Generated by scripts/l2j/extract-loot.mjs.', 'loot', loot);
write('template/l2Items.js', 'Real High Five items: id -> [name, type, grade, shop price, etc type]. Generated by scripts/l2j/extract-loot.mjs.', 'items', itemsOut);
write('template/l2Recipes.js', 'Real High Five craft recipes. Generated by scripts/l2j/extract-loot.mjs.', 'recipes', recipes);
const rows = Object.values(loot).reduce((n, r) => n + r.length, 0);
console.log({mobs: Object.keys(loot).length, wanted: wanted.size, dropRows: rows, items: Object.keys(itemsOut).length, recipes: recipes.length});
