// Real High Five symbols (hennas): the dye, the six stat changes, the price and who may wear it.
//
//   node scripts/l2j/extract-henna.mjs <hennaList.xml> <items dir>
//
// hennaList.xml: data/stats/hennaList.xml of a High Five datapack
// items dir    : data/stats/items (names of the dyes)
// Writes template/hennaData.js: [{dye, name, level, stats, wear: [dyes, adena], cancel: [dyes back, adena], who}].
import fs from 'node:fs';
import path from 'node:path';

const [hennaFile, itemDir] = process.argv.slice(2);
if (!hennaFile || !itemDir) { console.error('usage: node scripts/l2j/extract-henna.mjs <hennaList.xml> <items dir>'); process.exit(1); }
const walk = dir => fs.readdirSync(dir, {withFileTypes: true}).flatMap(e => e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]);
const names = new Map();
for (const file of walk(itemDir).filter(f => f.endsWith('.xml'))) {
  for (const m of fs.readFileSync(file, 'utf8').matchAll(/<item id="(\d+)" type="\w+" name="([^"]+)"/g)) names.set(+m[1], m[2].replaceAll('&apos;', "'"));
}

// A symbol lists the class ids that may wear it: the first and second classes of the three archetypes tell who that is.
const ARCHETYPES = {fighter: [1, 2], mage: [11, 12], priest: [15, 16]};
const rows = [];
for (const m of fs.readFileSync(hennaFile, 'utf8').matchAll(/<henna dyeId="(\d+)" dyeName="[^"]*" dyeItemId="(\d+)" dyeLevel="(\d+)">([\s\S]*?)<\/henna>/g)) {
  const body = m[4];
  const stats = {};
  for (const stat of body.matchAll(/(str|con|dex|int|men|wit)="(-?\d+)"/g)) if (+stat[2]) stats[stat[1].toUpperCase()] = +stat[2];
  const wear = body.match(/<wear count="(\d+)" fee="(\d+)"/), cancel = body.match(/<cancel count="(\d+)" fee="(\d+)"/);
  const classes = [...body.matchAll(/<classId>(\d+)<\/classId>/g)].map(x => +x[1]);
  rows.push({
    dye: +m[2], name: names.get(+m[2]) || `Dye ${m[2]}`, level: +m[3], stats,
    wear: [+wear[1], +wear[2]], cancel: [+cancel[1], +cancel[2]],
    who: Object.entries(ARCHETYPES).filter(([, ids]) => ids.some(id => classes.includes(id))).map(([name]) => name),
  });
}
fs.writeFileSync('template/hennaData.js', `// Real High Five symbols. Generated by scripts/l2j/extract-henna.mjs.\nexport default ${JSON.stringify(rows)};\n`);
const kinds = {};
for (const row of rows) kinds[row.who.join('+')] = (kinds[row.who.join('+')] || 0) + 1;
console.log(rows.length, 'symbols', kinds, 'sample:', rows[0]);
