"""Import High Five abnormal skills, original level tables and class learning trees."""
import json, re, html
from pathlib import Path
import xml.etree.ElementTree as ET
from PIL import Image
SOURCE='9fb01cb20513e55190cdde8d91e41be2c0914f84'
icons={p.stem.lower():p for p in Path('C:/Users/kubai/Desktop/icons').rglob('*.png')}
all_skills={}
def tree(e):
    return {'tag':e.tag,**e.attrib,**({'value':e.text.strip()} if e.text and e.text.strip() else {}),**({'children':[tree(c) for c in e]} if len(e) else {})}
for p in Path('.tmp/l2-high-five/all-skills').rglob('*.xml'):
    for s in ET.parse(p).getroot().findall('skill'):all_skills[int(s.get('id'))]=s
selected={id:s for id,s in all_skills.items() if s.findtext('operateType') in ['A2','A3','T','DA2'] or s.findtext('isDebuff') in ['true','#isDebuff'] or s.findtext('abnormalType')}
# Instant cancellation/cleansing belongs to this system as well.
for id,s in all_skills.items():
    if any(e.get('name','').startswith('Dispel') for e in s.findall('.//effect')):selected[id]=s
pending=list(selected)
while pending:
    s=selected[pending.pop()]
    for e in s.findall('.//effect'):
        if e.get('name') in ['CallSkill','TriggerSkillByDamageReceived']:
            for tag in ['skillId','triggeredSkillId']:
                value=e.findtext(tag,'')
                if value.isdigit() and int(value) in all_skills and int(value) not in selected:selected[int(value)]=all_skills[int(value)];pending.append(int(value))
definitions={};catalog=[];assets={}
for id,s in sorted(selected.items()):
    icon=(s.findtext('icon') or '').lower().replace('branchsys2.icon.','branchsys2.').replace('branchsys.icon.','branchsys.')
    if icon.startswith('#'):
        table=next((t for t in s.findall('table') if t.get('name','').lower()==icon),None)
        if table is not None and table.text:icon=table.text.split()[0].lower().replace('branchsys2.icon.','branchsys2.')
    if icon not in icons and 'icon.skill'+str(id).zfill(4) in icons:icon='icon.skill'+str(id).zfill(4)
    art=icon.replace('.','-') if icon in icons else None
    if art:assets[art]=icons[icon]
    kind='debuff' if s.findtext('isDebuff') in ['true','#isDebuff'] else 'buff'
    operate=s.findtext('operateType','A1')
    group='Дебаффы' if kind=='debuff' else 'Баффы'
    if operate=='T':group='Переключаемые умения'
    if s.get('name','').startswith('Song '):group='Песни'
    if s.get('name','').startswith('Dance '):group='Танцы'
    fields={c.tag:c.text.strip() for c in s if not len(c) and c.text and c.text.strip()}
    tables={t.get('name'):t.text.split() for t in s.findall('table') if t.text}
    effects=[tree(e) for e in s.findall('./effects/effect')]
    # Chance/conditional skills retain their conditions rather than becoming unconditional stats.
    definitions[id]={'id':id,'name':s.get('name'),'levels':int(s.get('levels','1')),'kind':kind,'operate':operate,'fields':fields,'tables':tables,'effects':effects,'conditions':[tree(e) for e in s.findall('conditions')],'group':group,'art':art}
    catalog.append({'id':id,'name':s.get('name'),'kind':kind,'group':group,'operate':operate,'levels':int(s.get('levels','1')),'abnormalType':fields.get('abnormalType'),'icon':icon or None,'art':art,'scope':'player' if id<2000 else 'item' if id<4000 else 'npc' if id<7000 else 'special'})
learn={};classes={}
for p in Path('.tmp/l2-high-five/players').rglob('classList.xml'):
    for row in ET.parse(p).getroot().findall('class'):classes[row.get('classId')]={'name':row.get('name'),'parent':row.get('parentClassId')}
for p in Path('.tmp/l2-high-five/players').rglob('*.xml'):
    if 'skillTrees' not in str(p):continue
    for t in ET.parse(p).getroot().findall('skillTree'):
        if t.get('type')!='classSkillTree':continue
        class_id=t.get('classId');learn.setdefault(class_id,[])
        for s in t.findall('skill'):
            id=int(s.get('skillId','0'))
            if id in definitions:learn[class_id].append({'id':id,'level':int(s.get('skillLevel','1')),'needLevel':int(s.get('getLevel','1')),'sp':int(s.get('levelUpSp','0')),'items':[dict(e.attrib) for e in s.findall('item')]})
Path('template/l2EffectSkills.js').write_text('// High Five source '+SOURCE+'. Generated by scripts/l2j/import-effects.py.\nexport const L2_EFFECT_SKILLS='+json.dumps(definitions,ensure_ascii=False,separators=(',',':'))+';\nexport const L2_EFFECT_LEARN='+json.dumps(learn,separators=(',',':'))+';\nexport const L2_CLASSES='+json.dumps(classes,separators=(',',':'))+';\n',encoding='utf-8')
dest=Path('webapp/art/l2-effects');dest.mkdir(parents=True,exist_ok=True)
for key,p in assets.items():
    with Image.open(p) as image:
        for size in [32,64,128]:image.convert('RGBA').resize((size,size),Image.Resampling.NEAREST).save(dest/f'{key}-{size}.webp',lossless=True)
Path('docs/l2-effects-references.json').write_text(json.dumps({'source':SOURCE,'effects':catalog,'missing':[r for r in catalog if not r['art']]},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
Path('webapp/art/l2-effects-art.js').write_text('// Generated High Five client icon allowlist.\nexport const L2_EFFECT_ART='+json.dumps({row['id']:row['art'] for row in catalog if row['art']},separators=(',',':'))+';\n'+'''
const byId=new Map(Object.entries(L2_EFFECT_ART).map(([id,art])=>[Number(id),art]));
export function l2EffectIcon(key){const id=Number(String(key).replace(/^(?:l2:|skill[_:-])/,'').split(':')[0]);const art=byId.get(id);return art?`<img class="mat-icon l2-client-icon" src="/art/l2-effects/${art}-32.webp" srcset="/art/l2-effects/${art}-64.webp 2x, /art/l2-effects/${art}-128.webp 4x" width="32" height="32" style="object-fit:contain;image-rendering:pixelated;flex-shrink:0" alt="" decoding="async" draggable="false">`:'';}
''',encoding='utf-8')
print(f'{len(definitions)} effect skills, {len(assets)} original images, {sum(not r["art"] for r in catalog)} source entries without supplied client art; {len(learn)} class trees.')
