"""Publish original PNG pixels as WebP; do not modify the existing equipment collection."""
import json, html
from pathlib import Path
from PIL import Image
plan=json.loads(Path('.tmp/l2-skill-fishing-plan.json').read_text(encoding='utf-8-sig'))
dest=Path('webapp/art/l2-extra');dest.mkdir(parents=True,exist_ok=True)
for asset in plan['assets']:
    with Image.open(asset['source']) as original:
        for size in (32,64,128):
            original.convert('RGBA').resize((size,size),Image.Resampling.NEAREST).save(dest/f"{asset['key']}-{size}.webp",lossless=True)
public={key:value for key,value in plan.items() if key!='assets'}
public['assets']=[{k:v for k,v in a.items() if k!='source'} for a in plan['assets']]
Path('docs/l2-skill-fishing-references.json').write_text(json.dumps(public,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
Path('webapp/art/l2-extra-art.js').write_text('// Original Lineage II pixels. Generated by scripts/l2j/publish-skill-fishing-icons.py.\n'+
    'export const L2_SKILL_ART=Object.freeze('+json.dumps(plan['skillArt'],ensure_ascii=False)+');\n'+
    'export const L2_FISHING_ART=Object.freeze('+json.dumps(plan['fishingArt'])+');\n'+'''
const published=new Set([...Object.values(L2_SKILL_ART),...Object.values(L2_FISHING_ART)]);
export function l2ExtraUrl(key,size=32){return published.has(key)?`/art/l2-extra/${key}-${[32,64,128].includes(size)?size:32}.webp`:null;}
function image(key){const src=l2ExtraUrl(key);return src?`<img class="mat-icon l2-client-icon" src="${src}" srcset="${l2ExtraUrl(key,64)} 2x, ${l2ExtraUrl(key,128)} 4x" width="32" height="32" style="object-fit:contain;image-rendering:pixelated;flex-shrink:0" alt="" decoding="async" draggable="false">`:'';}
export function l2SkillIcon(key){return image(L2_SKILL_ART[key]);}
export function l2FishingIcon(key){return image(L2_FISHING_ART[key]);}
''',encoding='utf-8')
groups={}
for row in plan['references']:groups.setdefault(row['group'],[]).append(row)
def card(row):
    name=row.get('name',row.get('key',''))
    detail=f"{row['referenceId']} · {row['reference']}" if 'referenceId' in row else str(row['id'])
    return f'<article data-search="{html.escape(name.lower()+" "+detail.lower(),quote=True)}"><img src="../webapp/art/l2-extra/{row["art"]}-32.webp" width="32" height="32" alt=""><div><b>{html.escape(name)}</b><small>{html.escape(detail)}</small><code>{html.escape(row.get("original",row.get("icon","")))}</code></div></article>'
groups['Рыбы, удочки, наживка, заряды, добыча и рецепты']=plan['fishingReferences']
body=''.join(f'<section><h2>{html.escape(group)} · {len(rows)}</h2><div class="grid">'+''.join(card(row) for row in rows)+'</div></section>' for group,rows in groups.items())
Path('docs/l2-skill-fishing-icons-preview.html').write_text('''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>L2 — навыки и рыбалка</title><style>
*{box-sizing:border-box}body{margin:0;padding:20px;background:#111411;color:#ded8be;font:15px system-ui}h1{font:26px Georgia;color:#ecd69c}h2{font-size:18px}a{color:#dec582}input{width:100%;padding:12px;background:#20251e;color:#eee;border:1px solid #726445;border-radius:4px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,270px),1fr));gap:8px}article{display:flex;align-items:center;gap:12px;min-width:0;padding:10px;background:#20231b;border:1px solid #4f4837}img{image-rendering:pixelated;flex-shrink:0}article div{min-width:0}small,code{display:block;color:#a8a391;font-size:11px;overflow-wrap:anywhere}b{font-size:13px}article[hidden]{display:none}
</style><h1>Lineage II · навыки и рыбалка</h1><p>Оригинальные изображения клиента, WebP 32×32. Баффы и рыболовные предметы сопоставлены по ID. Наши авторские навыки используют иконки близких по смыслу умений L2. ЛС: оригинальные общие значки активных, пассивных и срабатывающих умений.</p><p><a href="l2-assets-preview.html">Все ассеты</a> · <a href="l2-effects-preview.html">Все баффы и дебаффы High Five</a> · <a href="l2-skill-fishing-references.json">Список соответствий</a></p><input placeholder="Найти по названию, ID или умению L2" aria-label="Поиск">'''+body+'''<script>document.querySelector('input').addEventListener('input',e=>document.querySelectorAll('article').forEach(row=>row.hidden=!row.dataset.search.includes(e.target.value.trim().toLowerCase())))</script></html>''',encoding='utf-8')
print(f"Published {len(plan['assets'])} originals and {len(plan['fishingArt'])} fishing item mappings.")
