"""Publish the client icons of the real class skills (template/l2Classes.js) as WebP and map them by skill name.

    python scripts/l2j/publish-class-skill-icons.py [icons dir]

Writes webapp/art/l2-extra/icon-skillNNNN-{32,64,128}.webp (original pixels, nearest neighbour) and
webapp/art/l2-class-skill-art.js ({skill name: art key}), which webapp/art/l2-extra-art.js merges into L2_SKILL_ART.
"""
import json
import sys
from pathlib import Path
from PIL import Image

icons = Path(sys.argv[1] if len(sys.argv) > 1 else 'C:/Users/kubai/Desktop/icons')
source = Path('template/l2Classes.js').read_text(encoding='utf-8')
data = json.loads(source[source.index('export default ') + len('export default '):].rstrip().rstrip(';'))
dest = Path('webapp/art/l2-extra')
dest.mkdir(parents=True, exist_ok=True)
art = {}
missing = []
published = 0
for skill_id, skill in data['skills'].items():
    icon = (skill.get('icon') or '').lower()
    if not icon:
        icon = f'icon.skill{int(skill_id):04d}'
    path = icons / f'{icon}.png'
    if not path.exists():
        # the file names of the client are case sensitive on some systems
        match = next((p for p in icons.glob(f'{icon}*.png')), None) if icon else None
        path = match or path
    if not path.exists():
        # the client has no icon for a few skills (event skills): they share the plain skill icon of the game
        missing.append((skill_id, skill['name'], icon))
        art.setdefault(skill['name'], 'icon-skill0003')
        continue
    key = icon.replace('.', '-').lower()
    if skill['name'] not in art:
        art[skill['name']] = key
    if not (dest / f'{key}-32.webp').exists():
        with Image.open(path) as original:
            for size in (32, 64, 128):
                original.convert('RGBA').resize((size, size), Image.Resampling.NEAREST).save(dest / f'{key}-{size}.webp', lossless=True)
        published += 1
# the special skills of the Scryde server (template/scrydeSpells.js) that the client does not have take the icon of a kin skill
for name, like in {'Deadly Smash': 'Mortal Blow', 'Song of Spirit': 'Song of Vitality', 'Appetite Destruction': 'Chant of Victory', 'Mass Buff': 'Chant of Victory', 'Witchcraft': 'Drain Health', 'King Fury': 'Chant of Victory', 'Magnus Fury': 'Chant of Victory', 'Mental Weakness': 'Entangle', 'Touch of Eva': 'Shield of Faith', 'Magic Two-Handed Weapon Mastery': 'Weapon Mastery', 'Magic Wound': 'Weapon Mastery'}.items():
    if name not in art and like in art:
        art[name] = art[like]
Path('webapp/art/l2-class-skill-art.js').write_text(
    '// Original Lineage II client icons of the class skills, by skill name. Generated by scripts/l2j/publish-class-skill-icons.py.\n'
    'export const CLASS_SKILL_ART=Object.freeze(' + json.dumps(art, ensure_ascii=False, sort_keys=True) + ');\n', encoding='utf-8')
print(f'{len(art)} skill names mapped, {published} new icons published, {len(missing)} without a client icon')
for row in missing[:20]:
    print('  missing', row)
