// Prints template/seedHashes.js. Run after editing a template/*.js file (and bump
// its `version` in db/templates.js):  node scripts/templates/hash.mjs > template/seedHashes.js
import {TEMPLATES, hashTemplate} from '../../db/templates.js';

const rows = TEMPLATES.map(({key, source}) => `    ${key}: '${hashTemplate(JSON.parse(JSON.stringify(source)))}',`);
console.log(`// Content hashes of the template/*.js seeds. Generated by scripts/templates/hash.mjs;
// test/templates.test.js fails when a template changes without a version bump + new hash.
export default {
${rows.join('\n')}
};`);
