// Generated by `npm run art:build` (scripts/blender/art.js). Do not edit.
// JS rather than JSON because *.json is gitignored in this repo.
export const BUILD_ART = {
  "academy": {
    "light": [
      {
        "from": 2,
        "to": 6,
        "url": "/art/builds/academy/light-2-6.webp"
      }
    ]
  },
  "crystalLake": {
    "default": [
      {
        "from": 1,
        "to": 7,
        "url": "/art/builds/crystalLake/default-1-7.webp"
      },
      {
        "from": 8,
        "to": 15,
        "url": "/art/builds/crystalLake/default-8-15.webp"
      },
      {
        "from": 16,
        "to": 22,
        "url": "/art/builds/crystalLake/default-16-22.webp"
      },
      {
        "from": 23,
        "to": 30,
        "url": "/art/builds/crystalLake/default-23-30.webp"
      }
    ]
  },
  "forge": {
    "default": [
      {
        "from": 1,
        "to": 3,
        "url": "/art/builds/forge/default-1-3.webp"
      },
      {
        "from": 4,
        "to": 5,
        "url": "/art/builds/forge/default-4-5.webp"
      },
      {
        "from": 6,
        "to": 9,
        "url": "/art/builds/forge/default-6-9.webp"
      },
      {
        "from": 10,
        "to": 12,
        "url": "/art/builds/forge/default-10-12.webp"
      }
    ]
  },
  "goldMine": {
    "default": [
      {
        "from": 1,
        "to": 7,
        "url": "/art/builds/goldMine/default-1-7.webp"
      },
      {
        "from": 8,
        "to": 15,
        "url": "/art/builds/goldMine/default-8-15.webp"
      },
      {
        "from": 16,
        "to": 22,
        "url": "/art/builds/goldMine/default-16-22.webp"
      },
      {
        "from": 23,
        "to": 30,
        "url": "/art/builds/goldMine/default-23-30.webp"
      }
    ]
  },
  "ironDeposit": {
    "default": [
      {
        "from": 1,
        "to": 7,
        "url": "/art/builds/ironDeposit/default-1-7.webp"
      },
      {
        "from": 8,
        "to": 15,
        "url": "/art/builds/ironDeposit/default-8-15.webp"
      },
      {
        "from": 16,
        "to": 22,
        "url": "/art/builds/ironDeposit/default-16-22.webp"
      },
      {
        "from": 23,
        "to": 30,
        "url": "/art/builds/ironDeposit/default-23-30.webp"
      }
    ]
  },
  "palace": {
    "common": [
      {
        "from": 1,
        "to": 1,
        "url": "/art/builds/palace/common-1-1.webp"
      },
      {
        "from": 2,
        "to": 4,
        "url": "/art/builds/palace/common-2-4.webp"
      },
      {
        "from": 5,
        "to": 10,
        "url": "/art/builds/palace/common-5-10.webp"
      },
      {
        "from": 11,
        "to": 18,
        "url": "/art/builds/palace/common-11-18.webp"
      },
      {
        "from": 19,
        "to": 25,
        "url": "/art/builds/palace/common-19-25.webp"
      },
      {
        "from": 26,
        "to": 30,
        "url": "/art/builds/palace/common-26-30.webp"
      }
    ],
    "elven": [
      {
        "from": 1,
        "to": 1,
        "url": "/art/builds/palace/elven-1-1.webp"
      },
      {
        "from": 2,
        "to": 4,
        "url": "/art/builds/palace/elven-2-4.webp"
      },
      {
        "from": 5,
        "to": 10,
        "url": "/art/builds/palace/elven-5-10.webp"
      },
      {
        "from": 11,
        "to": 18,
        "url": "/art/builds/palace/elven-11-18.webp"
      },
      {
        "from": 19,
        "to": 25,
        "url": "/art/builds/palace/elven-19-25.webp"
      },
      {
        "from": 26,
        "to": 30,
        "url": "/art/builds/palace/elven-26-30.webp"
      }
    ],
    "royal": [
      {
        "from": 1,
        "to": 1,
        "url": "/art/builds/palace/royal-1-1.webp"
      },
      {
        "from": 2,
        "to": 4,
        "url": "/art/builds/palace/royal-2-4.webp"
      },
      {
        "from": 5,
        "to": 10,
        "url": "/art/builds/palace/royal-5-10.webp"
      },
      {
        "from": 11,
        "to": 18,
        "url": "/art/builds/palace/royal-11-18.webp"
      },
      {
        "from": 19,
        "to": 25,
        "url": "/art/builds/palace/royal-19-25.webp"
      },
      {
        "from": 26,
        "to": 30,
        "url": "/art/builds/palace/royal-26-30.webp"
      }
    ]
  },
  "traineeArea": {
    "default": [
      {
        "from": 1,
        "to": 5,
        "url": "/art/builds/traineeArea/default-1-5.webp"
      },
      {
        "from": 6,
        "to": 10,
        "url": "/art/builds/traineeArea/default-6-10.webp"
      },
      {
        "from": 11,
        "to": 19,
        "url": "/art/builds/traineeArea/default-11-19.webp"
      },
      {
        "from": 20,
        "to": 26,
        "url": "/art/builds/traineeArea/default-20-26.webp"
      },
      {
        "from": 27,
        "to": 30,
        "url": "/art/builds/traineeArea/default-27-30.webp"
      }
    ]
  }
};

/** Painting for a building at `level`; unknown styles fall back to the first one. */
export function buildArtUrl(id, level = 1, style = null) {
  const styles = BUILD_ART[id];
  if (!styles) return null;
  const stages = styles[style] || styles.default || Object.values(styles)[0];
  const lvl = Math.max(1, Number(level) || 1);
  const stage = stages.find(s => lvl >= s.from && lvl <= s.to) || (lvl < stages[0].from ? stages[0] : stages[stages.length - 1]);
  return stage.url;
}
