// Builds webapp/i18n/uz.js from the numbered translation files.
//
//   node scripts/i18n/extract.mjs   # refresh catalog.json when Russian text changes
//   node scripts/i18n/build.mjs     # merge scripts/i18n/uz/*.tsv into webapp/i18n/uz.js
//
// Each tsv line is `<catalog index>\t<Uzbek text>`. Phrases without a line are
// listed in untranslated.json (legacy chat help, LLM prompts) so a new
// untranslated phrase is noticed by the test instead of slipping by.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { placeholdersOf } from '../../webapp/i18n/engine.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const DIR = path.join(ROOT, 'scripts/i18n');
const CYRILLIC = /[А-Яа-яЁё]/;

const catalog = JSON.parse(fs.readFileSync(path.join(DIR, 'catalog.json'), 'utf8'));
const dictionary = {};
const problems = [];

for (const file of fs.readdirSync(path.join(DIR, 'uz')).filter(name => name.endsWith('.tsv')).sort()) {
  const lines = fs.readFileSync(path.join(DIR, 'uz', file), 'utf8').split('\n');
  lines.forEach((line, number) => {
    if (!line.trim()) return;
    const tab = line.indexOf('\t');
    const index = Number(line.slice(0, tab));
    const target = line.slice(tab + 1).replace(/\r$/, '');
    const where = `${file}:${number + 1}`;
    const source = catalog[index];
    if (tab < 0 || !Number.isInteger(index) || source === undefined) return problems.push(`${where}: bad index`);
    if (CYRILLIC.test(target)) return problems.push(`${where}: Cyrillic left in translation of "${source.slice(0, 40)}"`);
    if (placeholdersOf(source).join() !== placeholdersOf(target).join()) {
      return problems.push(`${where}: placeholders differ: ${placeholdersOf(source)} vs ${placeholdersOf(target)} ("${source.slice(0, 40)}")`);
    }
    if (dictionary[source] !== undefined) return problems.push(`${where}: duplicate index ${index}`);
    dictionary[source] = target;
  });
}

if (problems.length) {
  console.error(problems.join('\n'));
  process.exit(1);
}

const untranslated = catalog.filter(text => dictionary[text] === undefined);
const body = Object.entries(dictionary)
  .sort(([a], [b]) => a.localeCompare(b, 'ru'))
  .map(([source, target]) => `  ${JSON.stringify(source)}: ${JSON.stringify(target)},`)
  .join('\n');

fs.writeFileSync(path.join(ROOT, 'webapp/i18n/uz.js'),
  `// Uzbek (Latin) translation. Generated by scripts/i18n/build.mjs from scripts/i18n/uz/*.tsv.\n// Add or fix phrases in the tsv files (or in uz-extra.js) and rebuild.\nimport extra from './uz-extra.js';\n\nexport default {\n${body}\n  ...extra,\n};\n`);
if (!fs.existsSync(path.join(ROOT, 'webapp/i18n/uz-extra.js'))) {
  fs.writeFileSync(path.join(ROOT, 'webapp/i18n/uz-extra.js'), '// Phrases translated by hand after the catalog was built.\nexport default {\n};\n');
}
fs.writeFileSync(path.join(DIR, 'untranslated.json'), JSON.stringify(untranslated, null, 1));
console.log(`${Object.keys(dictionary).length} translated, ${untranslated.length} left in Russian on purpose`);
