#!/bin/sh
# Prepares the container for the bot, then runs the given command.
#
# 1. The bot reads and writes several JSON files next to its code (./x.json).
#    They are linked into the /app/state volume so they survive restarts.
# 2. config.js (token, admin id) is generated from the environment unless one
#    is mounted, so the token never has to be baked into the image.
# 3. db/db.js calls process.loadEnvFile('.env'); an empty file is enough when
#    the settings come from the container environment.
set -eu

APP=/app
STATE=${STATE_DIR:-/app/state}
mkdir -p "$STATE"

link_state() {
  name=$1
  default=$2
  if [ ! -e "$STATE/$name" ]; then
    if [ -f "$APP/$name" ] && [ ! -L "$APP/$name" ]; then
      cp "$APP/$name" "$STATE/$name"   # seed from a file shipped in the image
    else
      printf '%s' "$default" > "$STATE/$name"
    fi
  fi
  rm -f "$APP/$name"
  ln -s "$STATE/$name" "$APP/$name"
}

link_state trustedChats.json '[]'
link_state sessions.json '{}'
link_state titles.json '{}'
link_state bosses.json '{}'
link_state arenaRating.json '{}'
link_state arenaTempBots.json '[]'
link_state api.access.log ''

if [ ! -f "$APP/config.js" ]; then
  if [ -z "${BOT_TOKEN:-}" ]; then
    echo "entrypoint: BOT_TOKEN is not set (or mount your own /app/config.js)." >&2
    exit 1
  fi
  if [ -z "${ADMIN_ID:-}" ]; then
    echo "entrypoint: ADMIN_ID (your Telegram user id) is not set." >&2
    exit 1
  fi
  node -e '
    const q = JSON.stringify;
    const src = [
      "// Generated by docker/entrypoint.sh from the container environment.",
      `export let token = ${q(process.env.BOT_TOKEN)};`,
      `export let myId = ${Number(process.env.ADMIN_ID)};`,
      `export let giantBombApiKey = ${q(process.env.GIANT_BOMB_API_KEY || "")};`,
      "",
    ].join("\n");
    require("fs").writeFileSync("/app/config.js", src, { mode: 0o600 });
  '
fi

[ -f "$APP/.env" ] || : > "$APP/.env"

exec "$@"
