// Generates webapp/icon-set.js from Lucide (ISC license, https://lucide.dev).
//   npm i --no-save lucide-static && node scripts/ui/build-icons.mjs
// or point LUCIDE_DIR at any folder of Lucide *.svg files.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const dir = process.env.LUCIDE_DIR || path.join(root, 'node_modules/lucide-static/icons');

// Each emoji the UI used to show -> the icon that replaces it. Typographic
// glyphs (arrows, check mark, zodiac, card suits, ♂/♀) are text, not emoji, and stay.
const EMOJI = {
  '🪙': 'coin', '💰': 'hand-coins', '💎': 'gem', '⛏': 'pickaxe', '✦': 'sparkle', '✧': 'sparkle', '✨': 'sparkles',
  '⚔': 'swords', '🗡': 'sword', '🛡': 'shield', '🏹': 'bow-arrow', '🎯': 'target', '💥': 'bomb', '💢': 'zap', '⚡': 'zap',
  '🔥': 'flame', '❄': 'snowflake', '💨': 'wind', '💧': 'droplet', '🌿': 'leaf', '🗿': 'mountain', '🌫': 'cloud-fog',
  '👹': 'skull', '💀': 'skull', '☠': 'skull', '👻': 'ghost', '😈': 'angry', '👽': 'orbit', '💩': 'cloud', '💋': 'cherry', '🤏': 'hand',
  '🛫': 'plane-takeoff', '🚗': 'car', '🎰': 'cherry', '🎲': 'dices', '🎳': 'circle-dot', '⚽': 'goal', '🏀': 'volleyball', '🎮': 'gamepad-2',
  '🏆': 'trophy', '🥇': 'medal', '🥈': 'medal', '🥉': 'medal', '🎖': 'medal', '👑': 'crown', '⭐': 'star', '★': 'star',
  '❤': 'heart', '💚': 'heart', '💬': 'message-circle', '📨': 'mail', '✉': 'mail', '🔔': 'bell', '🔕': 'bell-off',
  '🤫': 'volume-x', '🤐': 'volume-x', '🔇': 'volume-x', '👤': 'user', '👥': 'users', '🤝': 'handshake', '🦹': 'venetian-mask',
  '🧙': 'wand-sparkles', '🪄': 'wand-sparkles', '🔮': 'orbit', '🧭': 'compass', '🪞': 'mirror-round',
  '🏰': 'castle', '🏛': 'landmark', '🏳': 'flag', '🌳': 'trees', '🏗': 'construction', '🔨': 'hammer', '⚒': 'hammer',
  '⚗': 'flask-conical', '🧪': 'flask-conical', '🔬': 'microscope', '🎒': 'backpack', '🧰': 'package-open', '🧺': 'shopping-basket',
  '🛒': 'shopping-cart', '💱': 'arrow-left-right', '🎁': 'gift', '🏷': 'tag', '🗝': 'key-round', '🔒': 'lock',
  '📜': 'scroll', '📝': 'notebook-pen', '📋': 'clipboard-list', '📖': 'book-open', '❔': 'circle-help', '⚙': 'settings',
  '✅': 'circle-check', '❌': 'x', '✚': 'plus', '➕': 'plus', '➖': 'minus', '⬆': 'arrow-up', '⬜': 'square',
  '🔹': 'droplet', '🔷': 'droplet', '🔸': 'flame', '🟡': 'circle', '⏳': 'hourglass', '⌕': 'search', '☰': 'menu',
  '↻': 'rotate-cw', '↺': 'rotate-ccw', '⛶': 'maximize',
};
// Hand-drawn icons that Lucide lacks or draws too finely for 14px use.
const CUSTOM = {
  coin: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5.5"/><path d="M12 9.5v5"/>',
};
// Icons used directly by name (navigation, header, feature cards).
const NAMED = [
  'castle', 'user-round', 'swords', 'dices', 'users', 'menu', 'mail', 'settings', 'maximize', 'house', 'trees', 'landmark',
  'shield', 'backpack', 'zap', 'package-open', 'sparkles', 'trophy', 'venetian-mask', 'shopping-cart', 'coin', 'arrow-left-right',
  'spade', 'handshake', 'gift', 'tag', 'orbit', 'sword', 'bell', 'message-circle', 'circle-help', 'volume-x', 'notebook-pen',
  'wand-sparkles', 'crown', 'chevron-right', 'lock', 'scroll', 'store',
];

const names = [...new Set([...Object.values(EMOJI), ...NAMED])].sort();
const icons = {};
for (const name of names) {
  if (CUSTOM[name]) { icons[name] = CUSTOM[name]; continue; }
  const file = path.join(dir, `${name}.svg`);
  if (!fs.existsSync(file)) throw new Error(`Lucide icon not found: ${name} (${file})`);
  const svg = fs.readFileSync(file, 'utf8');
  icons[name] = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '').replace(/ \/>/g, '/>').trim();
}
const out = `// Generated by scripts/ui/build-icons.mjs from Lucide (ISC license, https://lucide.dev). Do not edit by hand.
// 24x24 stroke icons: every inner string is drawn with stroke="currentColor" by icons.js.
export const ICONS = Object.freeze(${JSON.stringify(icons, null, 1).replace(/\n\s*/g, ' ').replace(/^\{ /, '{\n  ').replace(/", "/g, '",\n  "').replace(/ \}$/, '\n}')});
// Emoji (without the U+FE0F variation selector) -> icon name.
export const EMOJI_ICON = Object.freeze(${JSON.stringify(EMOJI)});
`;
fs.writeFileSync(path.join(root, 'webapp/icon-set.js'), out);
console.log(`icon-set.js: ${names.length} icons, ${Object.keys(EMOJI).length} emoji mapped`);
