import { FORGE_CATALOG, FORGE_RECIPES, MATERIAL_NAMES, SA_OPTIONS, DYNASTY_PROFILES, CATACOMBS, SEAL_STONES, ARMOR_SETS, fullHighGradeSet, equipPreview, addRaidReward, blessedEpicPreview, blessEpic, forgeItemInfo, forgeGear, forgeItemStats, dynastySetActive, craftPreview, craftForgeItem, masterworkPreview, refineMasterwork, unsealPreview, unsealForgeItem, saPreview, installSa, removeSa, shoulderPreview, installShoulder, sealExchangePreview, exchangeSealStones, farmCatacomb, equipForgeItem } from './economy-model.js';

export function createEconomyScreens({getState,windowHtml,row,section,button,img,ui,fmt,esc,toast}) {
  let saUid='forge-0',saId='acumen',mwUid='forge-1',unsealUid='forge-3',shoulderUid='forge-2',profile='enchanter',recipeId='dynastyGloves',zoneId='witch';
  let exchangeCounts={blue:0,green:0,red:0},craftResult='',farmResult='',lastResult='',cloakId='cloakFreya',cloakUid=null,epicId='freya',epicUid=null;
  const artwork = info => info.artPath||`../art/items/v1/catalog-${['S','S84'].includes(info.grade)?'s80':info.grade.toLowerCase()}-${info.art}-128.webp`;
  const name = item => `${item.epicTier==='blessed'?'Blessed · ':''}${item.variant==='soul'?'Душевный · ':''}${item.sealed?'Запечатано · ':''}${item.quality==='foundation'?'Foundation · ':item.quality==='masterwork'?'Masterwork · ':''}${forgeItemInfo(item).name}`;
  const stateTags = item => `<span class="forge-tags">${item.epicTier==='blessed'?'<span class="gold">Blessed</span>':''}${item.bound?'<span>Привязан</span>':''}${item.sealed?'<span>Печать</span>':''}${item.quality==='foundation'?'<span>Foundation</span>':''}${item.quality==='masterwork'?'<span class="gold">MW</span>':''}${item.sa?'<span class="positive">SA</span>':''}${item.shoulder?`<span>Плечи ${item.shoulder.tier}</span>`:''}${item.equipped?'<span class="positive">Надето</span>':''}</span>`;
  function gearList(filter,selected,screen) {
    const gear=getState().gear.filter(filter).filter(item=>screen!=='unseal'||forgeItemInfo(item).type!=='cloak'&&!forgeItemInfo(item).epic);
    return `<div class="forge-selection">${gear.map(item=>`<button type="button" class="forge-gear ${item.uid===selected?'selected':''}" data-action="forge-pick" data-uid="${item.uid}" data-screen="${screen}" aria-pressed="${item.uid===selected}"><span class="item-slot">${img(artwork(forgeItemInfo(item)))}</span><span><b>${esc(name(item))}</b><small>${forgeItemInfo(item).grade} · +${item.enchant}</small>${stateTags(item)}</span></button>`).join('')||'<p class="note">Подходящих предметов пока нет. Создайте их в кузнице.</p>'}</div>`;
  }
  function summary(item) {
    if(!item)return '<p class="note">Выберите предмет.</p>';
    const labels={pAtk:'Физ. атака · P. Atk',mAtk:'Маг. атака · M. Atk',pDef:'Физ. защита · P. Def',mDef:'Маг. защита · M. Def',castingSpeed:'Скорость магии'};
    return `<div class="inset">${row('Предмет',esc(forgeItemInfo(item).name))}${row('Грейд',forgeItemInfo(item).grade)}${row('Состояние',stateTags(item))}${Object.entries(forgeItemStats(item)).map(([key,value])=>row(labels[key]||key,fmt(value))).join('')}${item.sa?row('SA',SA_OPTIONS[item.sa].effect):''}${item.shoulder?row('Плечи',`${DYNASTY_PROFILES[item.shoulder.profile].name} · ${item.shoulder.tier}`)+row('Бонус плеч',item.equipped&&dynastySetActive(getState())?'Активен':'Нужен надетый полный комплект')+'<p class="note">Эффект плеч требует полного комплекта Династии: нагрудник, шлем, перчатки и сапоги.</p>':''}</div>`;
  }
  function costs(cost={}) {
    const state=getState();
    return `<div class="inset forge-cost">${cost.gold?row('Адена',`${fmt(state.gold)} / ${fmt(cost.gold)}`,state.gold<cost.gold?'negative':''):''}${cost.aa?row('Древняя адена · AA',`${fmt(state.aa)} / ${fmt(cost.aa)}`,state.aa<cost.aa?'negative':''):''}${Object.entries(cost.materials||{}).map(([key,count])=>row(MATERIAL_NAMES[key],`${fmt(state.materials[key]||0)} / ${fmt(count)}`,(state.materials[key]||0)<count?'negative':'')).join('')}${Object.entries(cost.soulCrystals||{}).map(([key,count])=>row(`Кристалл души · ${key}`,`${state.soulCrystals[key]||0} / ${count}`)).join('')}</div>`;
  }
  const warning = preview => preview.reason?`<p class="note negative">${esc(preview.reason)}</p>`:'';
  const message = () => lastResult?`<div class="result forge-operation-result" role="status">${esc(lastResult)}</div>`:'';
  const balance = () => `<div class="forge-wallet"><span>Адена <b>${fmt(getState().gold)}</b></span><span>AA <b>${fmt(getState().aa)}</b></span></div>`;
  const equippedControl = item => item?`${warning(equipPreview(getState(),item.uid))}<div class="actions">${button(item.equipped?'Снять предмет':'Надеть предмет',`forge-equip-${item.uid}`,'',!equipPreview(getState(),item.uid).allowed)}</div>`:'';
  function sa() {
    const state=getState(),item=forgeGear(state,saUid),info=forgeItemInfo(item),preview=saPreview(state,saUid,saId);
    return windowHtml('Кузнец · Кристалл души',`${gearList(item=>forgeItemInfo(item).type==='weapon',saUid,'sa')}${summary(item)}${equippedControl(item)}${section('Особая способность · один SA')}<div class="forge-options">${(info?.sa||[]).map(id=>`<button type="button" class="forge-option ${id===saId?'selected':''}" data-action="sa-option" data-value="${id}" aria-pressed="${id===saId}"><span class="soul-crystal ${SA_OPTIONS[id].color}">◆</span><span><b>${SA_OPTIONS[id].name}</b><small>${SA_OPTIONS[id].effect} · ${SA_OPTIONS[id].color}, ступень ${info.stage}</small></span></button>`).join('')}</div>${section('До → после')}<div class="inset">${row('SA',`${item?.sa?SA_OPTIONS[item.sa].name:'Не установлен'} → ${SA_OPTIONS[saId].name}`)}${row('Заточка',`+${item?.enchant||0} → +${item?.enchant||0}`)}${row('Результат',SA_OPTIONS[saId].effect)}</div>${section('Требуется для установки')}${costs(preview.cost)}${warning(preview)}${message()}<p class="note">SA, Masterwork и аугментация — отдельные улучшения. Снятие SA стоит 30 000 адены; кристалл не возвращается.</p><div class="actions">${button('Снять SA','sa-remove','',!item?.sa||item.equipped||state.gold<30000)}${button('Установить SA','sa-install','primary',!preview.allowed)}</div><div class="actions">${button('Характеристики','status')}</div>`);
  }
  function masterwork() {
    const state=getState(),item=forgeGear(state,mwUid),info=forgeItemInfo(item),preview=masterworkPreview(state,mwUid);
    return windowHtml('Маммон · Создание Masterwork',`${gearList(item=>item.quality!=='ordinary',mwUid,'masterwork')}${summary(item)}${section('Foundation → Masterwork')}<div class="forge-transform"><span>Заготовка<br><b>Foundation</b></span><em>→</em><span>Обработанный предмет<br><b class="gold">Masterwork</b></span></div><p class="note">Foundation получается при крафте. До обработки заготовку нельзя надеть. Качество и печать независимы: запечатанный Foundation станет запечатанным Masterwork.</p>${section('Особый бонус предмета')}<div class="inset">${Object.entries(info?.masterwork||{}).map(([key,value])=>row(({mAtk:'М. атака',mDef:'М. защита',castingSpeed:'Скорость магии'})[key]||key,'+'+value,'positive')).join('')}${row('Заточка / SA / плечи','Сохраняются')}${row('Печать',item?.sealed?'Сохранится':'Без печати')}</div>${section('Материалы Маммона')}${costs(preview.cost)}${warning(preview)}${message()}<div class="actions">${button('Крафт','craft')}${button('Обработать','mw-refine','primary',!preview.allowed)}</div><div class="actions">${button('Распечатка','unseal')}</div>`);
  }
  function craft() {
    const state=getState(),preview=craftPreview(state,recipeId),info=FORGE_CATALOG[recipeId];
    return windowHtml('Кузница · Запечатанный крафт',`<div class="forge-flow"><span>Рецепт</span><em>→</em><span>Крафт</span><em>→</em><span>Печать</span></div><div class="forge-selection">${FORGE_RECIPES.map(recipe=>`<button type="button" class="forge-gear ${recipe.id===recipeId?'selected':''}" data-action="forge-recipe" data-value="${recipe.id}"><span class="item-slot">${img(artwork(FORGE_CATALOG[recipe.id]))}</span><span><b>${FORGE_CATALOG[recipe.id].name}</b><small>${FORGE_CATALOG[recipe.id].grade} · рецепт ${recipe.rate}%</small></span></button>`).join('')}</div>${section('Выбранный рецепт')}<div class="inset">${row('Результат',esc(info.name))}${row('Обычный результат','Запечатанный предмет')}${row('Редкий результат','Запечатанный Foundation')}${row('Успех крафта',preview.recipe.rate+' %')}${row('Foundation при успехе',preview.recipe.foundationRate+' % · пример')}</div>${section('Будет потрачено за попытку')}${costs(preview.cost)}<p class="note">При неудаче расходуются материалы и адена. Foundation сначала обрабатывается в Masterwork, затем снимается печать.</p>${warning(preview)}${craftResult}<div class="forge-demo-actions">${button('Обычный · пример','craft-ordinary','primary',!preview.allowed)}${button('Foundation · пример','craft-foundation','',!preview.allowed)}${button('Неудача · пример','craft-failure','',!preview.allowed||preview.recipe.rate===100)}</div><div class="actions">${button('Masterwork','masterwork')}${button('Распечатка','unseal')}</div><p class="note">Выбор исхода служит для просмотра макета. Реальные рецепты и вероятность определяются сервером.</p>`);
  }
  function unseal() {
    const state=getState(),item=forgeGear(state,unsealUid),preview=unsealPreview(state,unsealUid),info=forgeItemInfo(item);
    return windowHtml('Распечатка · Маммон / Ишума',`<div class="forge-service"><b>${['S80','S84'].includes(info?.grade)?'Маэстро Ишума':'Кузнец Маммон'}</b><span>${['S80','S84'].includes(info?.grade)?'Gemstone S + обычная адена':'Древняя адена · AA'}</span></div>${gearList(item=>forgeItemInfo(item).type!=='weapon',unsealUid,'unseal')}${summary(item)}${section('Снятие печати')}<div class="forge-transform"><span>Запечатанный<br><b>${info?.grade||'—'}</b></span><em>→</em><span>Доступен для экипировки<br><b class="positive">Без печати</b></span></div><p class="note">Заточка, Masterwork и остальные свойства сохраняются. У Foundation сначала завершите обработку. Повторная распечатка не расходует ресурсы.</p>${section('Требуется для выбранного предмета')}${costs(preview.cost)}${warning(preview)}${message()}<div class="actions">${button('Камни → AA','aa')}${button('Распечатать','forge-unseal','primary',!preview.allowed)}</div>${equippedControl(item)}`);
  }
  function catacombs() {
    const state=getState(),zone=CATACOMBS.find(zone=>zone.id===zoneId);
    const allowed=state.level>=zone.level&&state.energy>=zone.energy&&state.hp>zone.damage;
    return windowHtml('Катакомбы · Камни печати',`<div class="catacomb-art" style="background-image:linear-gradient(transparent,#111a11),url('../art/hunt/zones/a-480.webp')"><span>SEVEN SIGNS</span><h3>${zone.name}</h3><small>Уровень ${zone.level}+ · Нежить и хранители печати</small></div><div class="forge-options">${CATACOMBS.map(z=>`<button type="button" class="forge-option ${z.id===zoneId?'selected':''}" data-action="catacomb-zone" data-value="${z.id}"><span class="zone-level">${z.level}</span><span><b>${z.name}</b><small>Энергия ${z.energy} · урон за бой ${z.damage}</small></span></button>`).join('')}</div><div class="inset">${row('Уровень героя',state.level)}${row('HP',fmt(state.hp))}${row('Энергия похода',state.energy+' / 12')}</div>${section('Награда победы · демонстрационная')}<div class="seal-stone-grid">${Object.entries(SEAL_STONES).map(([key,stone])=>`<div class="seal-stone-cell"><span style="--stone-color:${stone.color}">◆</span><b>+${zone[key]}</b><small>${stone.name}</small></div>`).join('')}</div><p class="note">Победа расходует энергию и HP, добавляет камни в общий инвентарь. Кристаллы души для SA и Gemstone S — другие материалы.</p>${farmResult}<div class="actions">${button('Обменять на AA','aa')}${button('Победа · пример','catacomb-farm','primary',!allowed)}</div>${!allowed?'<p class="note negative">Проверьте уровень, HP и оставшуюся энергию. Для нового примера нажмите «Сбросить пример».</p>':''}`);
  }
  function aa() {
    const state=getState(),preview=sealExchangePreview(state,exchangeCounts);
    return windowHtml('Жрец · Обмен камней на AA',`${balance()}<p class="note">Камни печати из катакомб обмениваются на древнюю адену. В адаптации WhitesLove обмен доступен постоянно.</p><div class="seal-exchange-list">${Object.entries(SEAL_STONES).map(([key,stone])=>`<label class="seal-exchange-row"><span class="seal-glyph" style="--stone-color:${stone.color}">◆</span><span><b>${stone.name}</b><small>Есть ${fmt(state.seals[key])} · 1 = ${stone.rate} AA</small></span><input type="number" min="0" max="${state.seals[key]}" step="1" data-seal-count="${key}" aria-label="Количество: ${stone.name}" value="${exchangeCounts[key]}"></label>`).join('')}</div><div class="actions">${button('Все камни','aa-all')}${button('Очистить','aa-clear')}</div>${section('Итог обмена')}<div class="inset">${row('Получите','<span id="aa-reward">'+fmt(preview.aa)+'</span> AA')}${row('После обмена','<span id="aa-after">'+fmt(state.aa+preview.aa)+'</span> AA')}</div><p class="note negative" id="aa-reason">${preview.reason}</p><p class="note">AA используется для распечатки A/S. Для S80/S84 нужны Gemstone S и обычная адена; эти валюты не подменяют друг друга.</p>${message()}<div class="actions">${button('Катакомбы','catacombs')}${button('Обменять','aa-exchange','primary',!preview.allowed)}</div><div class="actions">${button('К распечатке','unseal')}</div>`);
  }
  function shoulders() {
    const state=getState(),item=forgeGear(state,shoulderUid),nextTier=item?.shoulder?.tier===1?2:1,preview=shoulderPreview(state,shoulderUid,profile,nextTier);
    return windowHtml('Династия · Наплечники',`${gearList(item=>forgeItemInfo(item).set==='dynasty'&&forgeItemInfo(item).slot==='body',shoulderUid,'shoulders')}${summary(item)}${equippedControl(item)}${section('Специализация нагрудника')}<div class="forge-options">${Object.entries(DYNASTY_PROFILES).map(([id,p])=>`<button type="button" class="forge-option ${profile===id?'selected':''}" data-action="shoulder-profile" data-value="${id}" aria-pressed="${id===profile}"><span class="item-slot">${img(ui('shield'))}</span><span><b>${p.name}</b><small>${p.text}${p.family!==state.family?' · другой класс':''}</small></span></button>`).join('')}</div><div class="forge-flow"><span>Мантия Династии</span><em>→</em><span>Плечи I</span><em>→</em><span>Плечи II</span></div><p class="note">Плечи — улучшение нагрудника, а не отдельный слот экипировки. Эссенция I открывает специализацию, эссенция II усиливает её. Заточка и качество сохраняются.</p><div class="inset">${row('Следующая ступень',nextTier===2?'Плечи II':'Плечи I')}${row('Специализация',DYNASTY_PROFILES[profile].name)}${row('Бонус I',DYNASTY_PROFILES[profile].text)}${row('Бонус II',profile==='enchanter'?'М. атака +12%, скорость магии +7,5%':'MP +12%, сила лечения +7,5%')}</div>${section('Требуется для улучшения')}${costs(preview.cost)}${warning(preview)}${message()}<div class="actions">${button('Распечатка','unseal')}${button(nextTier===2?'Улучшить до II':'Установить плечи I','shoulder-install','primary',!preview.allowed)}</div><div class="actions">${button('Характеристики','status')}</div>`);
  }
  function inventorySection() {
    const state=getState();
    return `${section('Предметы кузницы · общее состояние')}<div class="forge-bag">${state.gear.map(item=>`<div class="forge-bag-item"><span class="item-slot">${img(artwork(forgeItemInfo(item)))}</span><div><b>${esc(name(item))}</b>${stateTags(item)}<small>${Object.entries(forgeItemStats(item)).map(([key,value])=>`${key} ${value}`).join(' · ')}</small>${!equipPreview(state,item.uid).allowed?`<small class="negative">${esc(equipPreview(state,item.uid).reason)}</small>`:''}</div><button type="button" data-action="forge-equip-${item.uid}" ${!equipPreview(state,item.uid).allowed?'disabled':''}>${item.equipped?'Снять':'Надеть'}</button></div>`).join('')}</div><div class="forge-shortcuts">${button('Крафт','craft')}${button('Распечатка','unseal')}${button('SA','sa')}${button('Плащи РБ','cloaks')}${button('Эпик → Blessed','epics')}</div>`;
  }
  function bonusRows(bonus) {
    const labels={maxHp:'Максимум HP',maxMp:'Максимум MP',mpRegen:'Восстановление MP',healPower:'Сила лечения',waterResist:'Защита от воды',darkResist:'Защита от тьмы',fireResist:'Защита от огня',mentalResist:'Ментальная защита, %',physicalCrit:'Физ. крит, %',evasion:'Уклонение',mAtkMul:'М. атака',attackSpeedMul:'Скорость атаки',castingSpeedMul:'Скорость магии'};
    return Object.entries(bonus||{}).map(([key,value])=>row(labels[key]||key,'+'+fmt(key.endsWith('Mul')?value*100:value)+(key.endsWith('Mul')?'%':''),'positive')).join('');
  }
  function cloaks() {
    const state=getState(),info=FORGE_CATALOG[cloakId],item=forgeGear(state,cloakUid),setId=fullHighGradeSet(state),set=ARMOR_SETS[setId||'dynasty'];
    const progress=set.slots.map(slot=>{const labels={body:'Нагрудник',helmet:'Шлем',gloves:'Перчатки',boots:'Сапоги'};const present=state.gear.some(i=>i.equipped&&!i.sealed&&i.quality!=='foundation'&&forgeItemInfo(i)?.set===(setId||'dynasty')&&forgeItemInfo(i).slot===slot);return row(labels[slot],present?'Надето':'Не хватает',present?'positive':'negative');}).join('');
    return windowHtml('Плащи · Наследие рейд-боссов',`${section('Слот плаща · полный комплект S80+')}<div class="inset">${row('Слот',setId?'Открыт · '+set.name:'Закрыт',setId?'positive':'negative')}${progress}</div><p class="note">Все части одного комплекта должны быть надеты и распечатаны. При снятии или замене части плащ автоматически снимается. В примере доступны Династия и Элегия.</p><div class="forge-options">${Object.entries(FORGE_CATALOG).filter(([,i])=>i.type==='cloak').map(([id,i])=>`<button type="button" class="forge-option ${cloakId===id?'selected':''}" data-action="cloak-option" data-value="${id}"><span class="item-slot">${img(artwork(i))}</span><span><b>${i.name}</b><small>${i.grade} · ${i.boss}</small></span></button>`).join('')}</div>${section(info.name)}<div class="inset">${row('Грейд',info.grade)}${row('Физ. защита',info.stats.pDef)}${bonusRows(info.bonus)}${row('Особый навык',info.call)}${row('Откат призыва','30 минут')}${row('Заточка / SA / аугментация','Недоступны')}</div><p class="note">Дроп РБ: запечатанный плащ, после распечатки можно передавать. Душевный плащ: квестовая версия, без печати, привязана к персонажу. Навык призыва показан в карточке; телепортация в макете не выполняется.</p>${section('Получение · демонстрация')}<div class="actions">${button('Дроп РБ · пример','cloak-drop','primary')}${button('Квест · пример','cloak-soul')}</div>${gearList(i=>forgeItemInfo(i).type==='cloak',cloakUid,'cloaks')}${item?summary(item)+row('Передача',item.bound||item.sealed?'Недоступна':'Разрешена')+equippedControl(item):''}${item?.sealed?costs(unsealPreview(state,item.uid).cost)+`<p class="note">Распечатка у Ткача · обычная адена. Цена — пример.</p><div class="actions">${button('Снять печать','cloak-unseal','primary',!unsealPreview(state,item.uid).allowed)}</div>`:''}${message()}<div class="actions">${button('Крафт комплекта','craft')}${button('Инвентарь','inventory')}</div>`);
  }
  function epics() {
    const state=getState(),info=FORGE_CATALOG[epicId],item=forgeGear(state,epicUid),selected=forgeItemInfo(item)||info,preview=blessedEpicPreview(state,epicUid);
    return windowHtml('Эпическая бижутерия · Blessed',`<p class="note">Фрея и Белеф добавлены в каталог. Универсальное улучшение всех эпиков — адаптация WhitesLove. Бонусы и цена ниже демонстрационные.</p><div class="forge-selection">${Object.entries(FORGE_CATALOG).filter(([,i])=>i.epic).map(([id,i])=>`<button type="button" class="forge-gear ${id===epicId?'selected':''}" data-action="epic-option" data-value="${id}"><span class="item-slot">${img(artwork(i))}</span><span><b>${i.name}</b><small>${i.grade} · ${i.boss}</small></span></button>`).join('')}</div><div class="actions">${button('Дроп эпика · пример','epic-drop','primary')}</div>${gearList(i=>forgeItemInfo(i).epic,epicUid,'epics')}${section('Обычный → Blessed')}<div class="inset">${row('Эпик',selected.name)}${row('Маг. защита',`${selected.stats.mDef} → ${selected.blessed.stats.mDef}`)}${row('Заточка',`+${item?.enchant||0} → +${item?.enchant||0}`)}${row('Предмет / привязка','Сохраняются')}${row('Результат','Blessed · '+selected.name)}</div>${section('Бонусы обычного эпика')}<div class="inset">${bonusRows(selected.bonus)}</div>${section('Бонусы Blessed')}<div class="inset">${bonusRows(selected.blessed.bonus)}</div><p class="note">Благословение заменяет обычные бонусы усиленными. Нужна бутыль души именно этого РБ; SA-кристалл и камни катакомб её не заменяют. Предмет требуется снять.</p>${item?summary(item)+equippedControl(item)+costs(preview.cost):'<p class="note">Получите эпик для демонстрации улучшения.</p>'}${warning(preview)}${message()}<div class="actions">${button('Улучшить до Blessed','epic-bless','primary',!preview.allowed)}${button('Характеристики','status')}</div>`);
  }
  function handle(action,node) {
    const state=getState();let result;
    if(action==='forge-pick'){const screen=node.dataset.screen;if(screen==='sa')saUid=node.dataset.uid;if(screen==='masterwork')mwUid=node.dataset.uid;if(screen==='unseal')unsealUid=node.dataset.uid;if(screen==='shoulders')shoulderUid=node.dataset.uid;if(screen==='cloaks')cloakUid=node.dataset.uid;if(screen==='epics'){epicUid=node.dataset.uid;epicId=forgeGear(state,epicUid).templateId;}lastResult='';return true;}
    if(action==='cloak-option'){cloakId=node.dataset.value;cloakUid=state.gear.find(i=>i.templateId===cloakId)?.uid||null;lastResult='';return true;}
    if(action==='epic-option'){epicId=node.dataset.value;epicUid=state.gear.find(i=>i.templateId===epicId)?.uid||null;lastResult='';return true;}
    if(action==='sa-option'){saId=node.dataset.value;lastResult='';return true;}
    if(action==='forge-recipe'){recipeId=node.dataset.value;craftResult='';return true;}
    if(action==='shoulder-profile'){profile=node.dataset.value;lastResult='';return true;}
    if(action==='catacomb-zone'){zoneId=node.dataset.value;farmResult='';return true;}
    if(action.startsWith('forge-equip-'))result=equipForgeItem(state,action.slice('forge-equip-'.length));
    else if(action==='sa-install')result=installSa(state,saUid,saId);
    else if(action==='sa-remove')result=removeSa(state,saUid);
    else if(action==='mw-refine'){result=refineMasterwork(state,mwUid);if(result.ok)unsealUid=mwUid;}
    else if(action==='forge-unseal')result=unsealForgeItem(state,unsealUid);
    else if(action==='cloak-drop'||action==='cloak-soul'){result=addRaidReward(state,cloakId,action==='cloak-soul'?'soul':'drop');if(result.ok)cloakUid=result.item.uid;}
    else if(action==='cloak-unseal')result=unsealForgeItem(state,cloakUid);
    else if(action==='epic-drop'){result=addRaidReward(state,epicId);if(result.ok)epicUid=result.item.uid;}
    else if(action==='epic-bless')result=blessEpic(state,epicUid);
    else if(action==='shoulder-install'){const item=forgeGear(state,shoulderUid);result=installShoulder(state,shoulderUid,profile,item?.shoulder?.tier===1?2:1);}
    else if(action.startsWith('craft-')){result=craftForgeItem(state,recipeId,action.slice(6));if(result.ok){craftResult=`<div class="result ${result.failed?'fail':''}" role="status">${result.failed?'Крафт не удался. Материалы потрачены.':esc(name(result.item))+' создан. Предмет добавлен в инвентарь.'}</div>`;if(result.item){unsealUid=result.item.uid;if(result.item.quality==='foundation')mwUid=result.item.uid;}}}
    else if(action==='catacomb-farm'){result=farmCatacomb(state,zoneId);if(result.ok)farmResult=`<div class="result" role="status">Победа! Камни печати добавлены: ${Object.entries(result.drops).map(([key,count])=>`${SEAL_STONES[key].name} +${count}`).join(', ')}.</div>`;}
    else if(action==='aa-all'){exchangeCounts={...state.seals};lastResult='';return true;}
    else if(action==='aa-clear'){exchangeCounts={blue:0,green:0,red:0};lastResult='';return true;}
    else if(action==='aa-exchange'){result=exchangeSealStones(state,exchangeCounts);if(result.ok){exchangeCounts={blue:0,green:0,red:0};lastResult=`Получено ${fmt(result.aa)} AA.`;}}
    else return false;
    if(result?.ok){if(!['aa-exchange','catacomb-farm'].includes(action)&&!action.startsWith('craft-'))lastResult=result.removedCloaks?.length?'Комплект разобран. Плащ снят и остался в инвентаре.':'Готово. Предмет и ресурсы обновлены.';toast(result.failed?'Показан неудачный исход крафта.':'Демонстрационное состояние обновлено.');}
    else toast(result?.reason||'Действие недоступно.');
    return true;
  }
  function input(node) {
    const key=node.dataset.sealCount;if(!key)return false;
    exchangeCounts[key]=node.value===''?0:Number(node.value);
    const preview=sealExchangePreview(getState(),exchangeCounts);
    document.getElementById('aa-reward').textContent=fmt(preview.aa);document.getElementById('aa-after').textContent=fmt(getState().aa+preview.aa);
    document.getElementById('aa-reason').textContent=preview.reason;
    document.querySelector('[data-action="aa-exchange"]').disabled=!preview.allowed;return true;
  }
  function reset(){saUid='forge-0';saId='acumen';mwUid='forge-1';unsealUid='forge-3';shoulderUid='forge-2';profile='enchanter';recipeId='dynastyGloves';zoneId='witch';exchangeCounts={blue:0,green:0,red:0};craftResult='';farmResult='';lastResult='';cloakId='cloakFreya';cloakUid=null;epicId='freya';epicUid=null;}
  return {renderers:{sa,masterwork,craft,unseal,catacombs,aa,shoulders,cloaks,epics},handle,input,reset,inventorySection,balance};
}
